import * as v from "valibot"

export const demoFixtureStateSchema = v.picklist([
  "success",
  "empty",
  "loading",
  "error",
  "permission-denied",
  "passkey-permission-denied",
  "passkey-ceremony-failure",
  "passkey-pending",
  "passkey-unsupported",
  "mfa-continuation",
  "mfa-enroll",
  "mfa-loading",
  "mfa-optional",
  "mfa-retry",
  "mfa-satisfied",
  "mfa-setup-unavailable",
  "expired",
  "replayed",
  "accepted",
  "declined",
  "one-time",
  "redacted",
  "cross-tenant",
  "continuing",
  "fatal",
  "password-change-expired",
  "recovery-fatal",
  "recovery-loading",
  "reset-invalid",
  "reset-loading",
  // Guarded impersonation states.
  "assurance-required",
  "active",
  "expiring",
  "nested-rejected",
  "ended",
])

export type DemoFixtureState = v.InferOutput<typeof demoFixtureStateSchema>
