export const userEventTypes = {
  created: "user.created",
  deleted: "user.deleted",
  emailChangeFailed: "user.email_change_failed",
  emailChangeRequested: "user.email_change_requested",
  emailChangeVerified: "user.email_change_verified",
  emailChanged: "user.email_changed",
  emailAddressAdded: "user.email_address_added",
  emailAddressPrimarySet: "user.email_address_primary_set",
  emailAddressRemoved: "user.email_address_removed",
  emailAddressVerificationFailed: "user.email_address_verification_failed",
  emailAddressVerificationRequested: "user.email_address_verification_requested",
  emailAddressVerified: "user.email_address_verified",
  emailVerificationChanged: "user.email_verification_changed",
  phoneNumberChanged: "user.phone_number_changed",
  profileUpdated: "user.profile_updated",
  registrationVerificationChanged: "user.registration_verification_changed",
  stateChanged: "user.state_changed",
} as const
