import type { ErrorCatalogEntry } from "../../../platform/errors/errorCatalogEntrySchema.js"

export const projectsErrorCatalog = [
  { code: "projects.invalid", httpStatus: 400, retryable: false },
  { code: "projects.empty-patch", httpStatus: 400, retryable: false },
  { code: "projects.invalid-page", httpStatus: 400, retryable: false },
  { code: "projects.invalid-cursor", httpStatus: 400, retryable: false },
  { code: "projects.not-found", httpStatus: 404, retryable: false },
  { code: "projects.unauthorized", httpStatus: 401, retryable: false },
  { code: "projects.forbidden", httpStatus: 403, retryable: false },
  { code: "projects.conflict", httpStatus: 409, retryable: false },
  { code: "projects.already-exists", httpStatus: 409, retryable: false },
  { code: "projects.not-active", httpStatus: 409, retryable: false },
  { code: "projects.removed", httpStatus: 409, retryable: false },
  { code: "projects.cannot-change", httpStatus: 409, retryable: false },
  { code: "projects.read-failed", httpStatus: 503, retryable: true },
  { code: "projects.write-failed", httpStatus: 503, retryable: true },
  { code: "projects.event-invalid", httpStatus: 500, retryable: false },
  { code: "projects.tenant-mismatch", httpStatus: 404, retryable: false },
  { code: "projects.organization-not-found", httpStatus: 404, retryable: false },
  { code: "projects.organization-not-active", httpStatus: 409, retryable: false },
  { code: "projects.membership-required", httpStatus: 403, retryable: false },
  { code: "projects.authorization-required", httpStatus: 401, retryable: false },
  { code: "projects.timestamp-invalid", httpStatus: 500, retryable: false },
  { code: "projects.role-invalid", httpStatus: 400, retryable: false },
  { code: "projects.application-invalid", httpStatus: 400, retryable: false },
  { code: "projects.grant-invalid", httpStatus: 400, retryable: false },
  { code: "projects.name-invalid", httpStatus: 400, retryable: false },
  { code: "projects.role-keys-invalid", httpStatus: 400, retryable: false },
  { code: "projects.role-keys-duplicate", httpStatus: 409, retryable: false },
  { code: "projects.request-invalid", httpStatus: 400, retryable: false },
  { code: "projects.internal", httpStatus: 500, retryable: false },
] as const satisfies readonly ErrorCatalogEntry[]
