import * as v from "valibot"

export const accountSecurityHistoryItemSchema = v.strictObject({
  category: v.picklist([
    "email_changes",
    "impersonation",
    "linked_identities",
    "mfa",
    "passwords",
    "passkeys",
    "refresh_tokens",
    "sessions",
  ]),
  displayCode: v.picklist([
    "email_change.changed",
    "email_change.failed",
    "email_change.requested",
    "email_change.verified",
    "impersonation.ended",
    "impersonation.started",
    "linked_identity.linked",
    "linked_identity.unlinked",
    "mfa.challenge.completed",
    "mfa.challenge.failed",
    "mfa.challenge.started",
    "mfa.recovery_code.used",
    "mfa.recovery_codes.generated",
    "mfa.totp.enrollment.confirmed",
    "mfa.totp.enrollment.started",
    "mfa.totp.removed",
    "mfa.totp.verified",
    "passkey.authentication_completed",
    "passkey.authentication_started",
    "passkey.credential_revoked",
    "passkey.credential_used",
    "passkey.registration_completed",
    "passkey.registration_started",
    "password.credential_changed",
    "password.email_verified",
    "password.locked",
    "password.login_failed",
    "password.login_succeeded",
    "password.recovered",
    "password.recovery_requested",
    "password.unlocked",
    "password.whatsapp_verified",
    "refresh_token.access_revoked",
    "refresh_token.family_revoked",
    "session.created",
    "session.revoked",
    "session.revoked_all",
    "session.rotated",
  ]),
  id: v.pipe(v.string(), v.minLength(1), v.maxLength(256)),
  occurredAt: v.pipe(v.number(), v.integer(), v.minValue(0)),
})

export type AccountSecurityHistoryItem = v.InferOutput<typeof accountSecurityHistoryItemSchema>
