export const oidcCodelineSecretRotateFailureExitCodes: ReadonlyMap<string, number> = new Map([
  ["oidc.codeline-secret-rotate.input-invalid", 40],
  ["oidc.codeline-secret-rotate.realm-not-found", 41],
  ["oidc.codeline-secret-rotate.realm-ambiguous", 42],
  ["oidc.codeline-secret-rotate.realm-inactive", 43],
  ["oidc.codeline-secret-rotate.api-unauthorized", 44],
  ["oidc.codeline-secret-rotate.api-unreachable", 45],
  ["oidc.codeline-secret-rotate.api-invalid-response", 46],
  ["oidc.codeline-secret-rotate.client-not-found", 47],
  ["oidc.codeline-secret-rotate.client-ambiguous", 48],
  ["oidc.codeline-secret-rotate.client-inactive", 49],
  ["oidc.codeline-secret-rotate.client-public", 50],
  ["oidc.codeline-secret-rotate.client-name-mismatch", 51],
  ["oidc.codeline-secret-rotate.client-callback-mismatch", 52],
  ["oidc.codeline-secret-rotate.client-cardinality-mismatch", 53],
  ["oidc.codeline-secret-rotate.rotation-rejected", 54],
  ["oidc.codeline-secret-rotate.envelope-invalid", 55],
  ["oidc.codeline-secret-rotate.internal-failed", 56],
])
