export const oidcCodelineProductionOrganizationIdGetFailureExitCodes: ReadonlyMap<string, number> = new Map([
  ["oidc.codeline-organization-id-get.input-invalid", 40],
  ["oidc.codeline-organization-id-get.realm-not-found", 41],
  ["oidc.codeline-organization-id-get.realm-ambiguous", 42],
  ["oidc.codeline-organization-id-get.realm-inactive", 43],
  ["oidc.codeline-organization-id-get.organization-not-found", 44],
  ["oidc.codeline-organization-id-get.organization-ambiguous", 45],
  ["oidc.codeline-organization-id-get.organization-inactive", 46],
  ["oidc.codeline-organization-id-get.human-ambiguous", 47],
  ["oidc.codeline-organization-id-get.human-conflict", 48],
  ["oidc.codeline-organization-id-get.human-deleted", 49],
  ["oidc.codeline-organization-id-get.human-inactive", 50],
  ["oidc.codeline-organization-id-get.machine-conflict", 51],
  ["oidc.codeline-organization-id-get.membership-elevated", 52],
  ["oidc.codeline-organization-id-get.membership-missing", 53],
  ["oidc.codeline-organization-id-get.membership-ambiguous", 54],
  ["oidc.codeline-organization-id-get.membership-role-invalid", 55],
  ["oidc.codeline-organization-id-get.api-unauthorized", 56],
  ["oidc.codeline-organization-id-get.api-unreachable", 57],
  ["oidc.codeline-organization-id-get.api-invalid-response", 58],
  ["oidc.codeline-organization-id-get.internal-failed", 59],
])
