export const eventSecurityEventDefinitionByType = {
  "external_identity.linked": {
    category: "linked_identities",
    displayCode: "linked_identity.linked",
    productionIntegrations: ["externalIdentityCallback", "externalIdentityLinkComplete"],
    subject: "user",
  },
  "external_identity.unlinked": {
    category: "linked_identities",
    displayCode: "linked_identity.unlinked",
    productionIntegrations: ["externalIdentityUnlink"],
    subject: "user",
  },
  "mfa.challenge.completed": {
    category: "mfa",
    displayCode: "mfa.challenge.completed",
    productionIntegrations: ["mfaChallengeComplete"],
    subject: "user",
  },
  "mfa.challenge.failed": {
    category: "mfa",
    displayCode: "mfa.challenge.failed",
    productionIntegrations: ["mfaChallengeComplete"],
    subject: "user",
  },
  "mfa.challenge.started": {
    category: "mfa",
    displayCode: "mfa.challenge.started",
    productionIntegrations: ["mfaLoginChallengeStart"],
    subject: "user",
  },
  "mfa.recovery_code.used": {
    category: "mfa",
    displayCode: "mfa.recovery_code.used",
    productionIntegrations: ["mfaChallengeComplete", "mfaRecoveryCodeVerify"],
    subject: "user",
  },
  "mfa.recovery_codes.generated": {
    category: "mfa",
    displayCode: "mfa.recovery_codes.generated",
    productionIntegrations: ["mfaRecoveryCodesGenerate"],
    subject: "user",
  },
  "mfa.totp.enrollment.confirmed": {
    category: "mfa",
    displayCode: "mfa.totp.enrollment.confirmed",
    productionIntegrations: ["mfaTotpEnrollmentConfirm"],
    subject: "user",
  },
  "mfa.totp.enrollment.started": {
    category: "mfa",
    displayCode: "mfa.totp.enrollment.started",
    productionIntegrations: ["mfaTotpEnrollmentStart"],
    subject: "user",
  },
  "mfa.totp.removed": {
    category: "mfa",
    displayCode: "mfa.totp.removed",
    productionIntegrations: ["mfaTotpEnrollmentRemove"],
    subject: "user",
  },
  "mfa.totp.verified": {
    category: "mfa",
    displayCode: "mfa.totp.verified",
    productionIntegrations: ["mfaTotpVerify"],
    subject: "user",
  },
  "oidc.access_token_revoked": {
    category: "refresh_tokens",
    displayCode: "refresh_token.access_revoked",
    productionIntegrations: ["oidcTokenRevoke", "oidcLogout", "oidcRefreshTokenFamilyRevokeExecute"],
    subject: "user",
  },
  "oidc.refresh_token_family_revoked": {
    category: "refresh_tokens",
    displayCode: "refresh_token.family_revoked",
    productionIntegrations: ["oidcTokenRevoke", "oidcLogout", "oidcRefreshTokenFamilyRevokeExecute"],
    subject: "user",
  },
  "password.credential_changed": {
    category: "passwords",
    displayCode: "password.credential_changed",
    productionIntegrations: [
      "passwordRegister",
      "passwordChange",
      "passwordCredentialReplace",
      "passwordRecoveryComplete",
    ],
    subject: "user",
  },
  "password.email_verified": {
    category: "passwords",
    displayCode: "password.email_verified",
    productionIntegrations: ["passwordEmailVerify"],
    subject: "user",
  },
  "password.login_failed": {
    category: "passwords",
    displayCode: "password.login_failed",
    productionIntegrations: ["passwordLogin"],
    subject: "user",
  },
  "password.login_succeeded": {
    category: "passwords",
    displayCode: "password.login_succeeded",
    productionIntegrations: ["passwordLogin"],
    subject: "user",
  },
  "password.locked": {
    category: "passwords",
    displayCode: "password.locked",
    productionIntegrations: ["passwordLogin"],
    subject: "user",
  },
  "password.recovered": {
    category: "passwords",
    displayCode: "password.recovered",
    productionIntegrations: ["passwordRecoveryComplete"],
    subject: "user",
  },
  "password.recovery_requested": {
    category: "passwords",
    displayCode: "password.recovery_requested",
    productionIntegrations: ["passwordRecoveryRequest"],
    subject: "user",
  },
  "password.unlocked": {
    category: "passwords",
    displayCode: "password.unlocked",
    productionIntegrations: ["passwordLogin", "passwordRecoveryComplete"],
    subject: "user",
  },
  "password.whatsapp_verified": {
    category: "passwords",
    displayCode: "password.whatsapp_verified",
    productionIntegrations: ["passwordWhatsappVerify"],
    subject: "user",
  },
  "passkey.authentication_completed": {
    category: "passkeys",
    displayCode: "passkey.authentication_completed",
    productionIntegrations: ["passkeyAuthenticationComplete"],
    subject: "user",
  },
  "passkey.authentication_started": {
    category: "passkeys",
    displayCode: "passkey.authentication_started",
    productionIntegrations: ["passkeyAuthenticationStart"],
    subject: "user",
  },
  "passkey.credential_revoked": {
    category: "passkeys",
    displayCode: "passkey.credential_revoked",
    productionIntegrations: ["passkeyCredentialRevoke"],
    subject: "user",
  },
  "passkey.credential_used": {
    category: "passkeys",
    displayCode: "passkey.credential_used",
    productionIntegrations: ["passkeyAuthenticationComplete"],
    subject: "user",
  },
  "passkey.registration_completed": {
    category: "passkeys",
    displayCode: "passkey.registration_completed",
    productionIntegrations: ["passkeyRegistrationComplete"],
    subject: "user",
  },
  "passkey.registration_started": {
    category: "passkeys",
    displayCode: "passkey.registration_started",
    productionIntegrations: ["passkeyRegistrationStart"],
    subject: "user",
  },
  "session.created": {
    category: "sessions",
    displayCode: "session.created",
    productionIntegrations: ["sessionIssue"],
    subject: "session_user",
  },
  "session.revoked": {
    category: "sessions",
    displayCode: "session.revoked",
    productionIntegrations: ["sessionRevoke", "impersonationEnd", "oidcLogout"],
    subject: "session_user",
  },
  "session.revoked_all": {
    category: "sessions",
    displayCode: "session.revoked_all",
    productionIntegrations: ["sessionRevokeAll"],
    subject: "session_user",
  },
  "session.rotated": {
    category: "sessions",
    displayCode: "session.rotated",
    productionIntegrations: [
      "sessionRotate",
      "sessionRecentResume",
      "mfaChallengeComplete",
      "passkeyAuthenticationComplete",
    ],
    subject: "session_user",
  },
  "user.email_change_failed": {
    category: "email_changes",
    displayCode: "email_change.failed",
    productionIntegrations: ["userEmailChangeVerify"],
    subject: "user",
  },
  "user.email_change_requested": {
    category: "email_changes",
    displayCode: "email_change.requested",
    productionIntegrations: ["userEmailChangeStart", "userEmailChangeResend"],
    subject: "user",
  },
  "user.email_change_verified": {
    category: "email_changes",
    displayCode: "email_change.verified",
    productionIntegrations: ["userEmailChangeVerify"],
    subject: "user",
  },
  "user.email_changed": {
    category: "email_changes",
    displayCode: "email_change.changed",
    productionIntegrations: ["userEmailChangeVerify"],
    subject: "user",
  },
  "impersonation.ended": {
    category: "impersonation",
    displayCode: "impersonation.ended",
    productionIntegrations: ["impersonationEnd", "sessionRevoke"],
    subject: "impersonated_user",
  },
  "impersonation.started": {
    category: "impersonation",
    displayCode: "impersonation.started",
    productionIntegrations: ["impersonationStart"],
    subject: "impersonated_user",
  },
} as const
