import type { ProductionRouteContract } from "./productionRouteContract.js"

export const productionRouteContractMap = {
  login: {
    feature: "login",
    guard: { authentication: "public", organization: "not-required", permission: null, realm: "required" },
    path: "/login",
    screens: [
      {
        contracts: ["organizations.discovery", "organizations.login-policy", "sessions.recent"],
        key: "chooser",
        path: "/login",
        title: "login.chooser.title",
      },
      { contracts: ["passwords.login"], key: "password", path: "/login/password", title: "shell.nav.passwordSignIn" },
      {
        contracts: ["email-otp.start", "email-otp.verify"],
        key: "email-otp",
        path: "/login/email-otp",
        title: "shell.nav.emailOtpSignIn",
      },
      {
        contracts: ["whatsapp-otp.availability", "whatsapp-otp.start"],
        key: "whatsapp-otp",
        path: "/login/whatsapp-otp",
        title: "login.whatsappOtp.title",
      },
      {
        contracts: ["whatsapp-otp.resend", "whatsapp-otp.verify"],
        key: "whatsapp-otp-code",
        path: "/login/whatsapp-otp/code",
        title: "login.whatsappOtp.codeTitle",
      },
      {
        contracts: ["passkeys.authenticate"],
        key: "passkey",
        path: "/login/passkey",
        title: "shell.nav.passkeySignIn",
      },
      {
        contracts: ["external-identities.authenticate"],
        key: "external-identity",
        path: "/login/idp",
        title: "shell.nav.externalIdentitySignIn",
      },
      { contracts: ["mfa.challenge"], key: "mfa", path: "/login/mfa", title: "shell.nav.mfaSignIn" },
      {
        contracts: ["passwords.recovery.request", "passwords.recovery.complete"],
        key: "recovery",
        path: "/login/password/forgot",
        title: "shell.nav.passwordRecovery",
      },
      { contracts: ["passwords.register"], key: "register", path: "/login/register", title: "shell.nav.registration" },
      {
        contracts: ["passwords.verify-email"],
        key: "verify-email",
        path: "/login/verify-email",
        title: "shell.nav.verifyEmail",
      },
      {
        contracts: ["oidc.interaction"],
        key: "consent",
        path: "/login/consent",
        title: "shell.nav.applicationConsent",
      },
      { contracts: ["oidc.logout"], key: "logout", path: "/login/logout", title: "shell.nav.logout" },
    ],
  },
  consent: {
    feature: "oidc",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/consent",
    screens: [
      {
        contracts: ["oidc.authorization", "oidc.consent"],
        key: "consent",
        path: "/consent",
        title: "shell.nav.applicationConsent",
      },
    ],
  },
  account: {
    feature: "account",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/account",
    screens: [
      { contracts: ["account.overview"], key: "overview", path: "/account", title: "shell.nav.account" },
      { contracts: ["account.profile"], key: "profile", path: "/account/profile", title: "shell.nav.profile" },
      { contracts: ["account.email"], key: "email", path: "/account/email", title: "shell.nav.emailAddress" },
      { contracts: ["account.password"], key: "password", path: "/account/password", title: "shell.nav.password" },
      { contracts: ["account.delete"], key: "delete", path: "/account/delete", title: "shell.nav.deleteAccount" },
      {
        contracts: ["organizations.list", "organizations.switch"],
        key: "organizations",
        path: "/account/organizations",
        title: "shell.nav.myOrganizations",
      },
      {
        contracts: ["account.effective-access"],
        key: "effective-access",
        path: "/account/effective-access",
        title: "shell.nav.effectiveAccess",
      },
      {
        contracts: ["sessions.list", "sessions.revoke"],
        key: "sessions",
        path: "/account/sessions",
        title: "shell.nav.sessionsDevices",
      },
      {
        contracts: ["passkeys.list", "passkeys.revoke"],
        key: "passkeys",
        path: "/account/passkeys",
        title: "shell.nav.passkeys",
      },
      {
        contracts: ["mfa.list", "mfa.enroll", "mfa.revoke"],
        key: "factors",
        path: "/account/factors",
        title: "shell.nav.mfa",
      },
      {
        contracts: ["mfa.recovery-codes"],
        key: "recovery-codes",
        path: "/account/recovery-codes",
        title: "shell.nav.recoveryCodes",
      },
      {
        contracts: [
          "external-identities.list",
          "external-identities.providers",
          "external-identities.link-start",
          "external-identities.link-callback",
          "external-identities.link-complete",
          "external-identities.unlink",
        ],
        key: "identities",
        path: "/account/identities",
        title: "shell.nav.linkedIdentities",
      },
      {
        contracts: ["oidc.refresh-tokens.list", "oidc.refresh-tokens.revoke"],
        key: "refresh-tokens",
        path: "/account/refresh-tokens",
        title: "shell.nav.refreshTokens",
      },
      {
        contracts: ["oidc.consents.list", "oidc.consents.revoke"],
        key: "consents",
        path: "/account/consents",
        title: "shell.nav.applicationConsents",
      },
    ],
  },
  invitations: {
    feature: "organizations",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/invitations",
    screens: [
      {
        contracts: ["organizations.invitations.accept", "organizations.invitations.decline"],
        key: "overview",
        path: "/invitations",
        title: "shell.nav.invitations",
      },
      {
        contracts: ["organizations.invitations.accept", "organizations.invitations.decline"],
        key: "accept",
        path: "/invitations/accept",
        title: "shell.nav.acceptInvitation",
      },
    ],
  },
  admin: {
    feature: "admin",
    guard: { authentication: "required", organization: "not-required", permission: "realm.read", realm: "required" },
    path: "/admin",
    screens: [
      {
        contracts: ["sessions.admin-sign-in"],
        guard: { authentication: "public", organization: "not-required", permission: null, realm: "required" },
        key: "sign-in",
        path: "/admin/sign-in",
        title: "shell.nav.administratorSignIn",
      },
      { contracts: ["realms.get"], key: "overview", path: "/admin", title: "admin.navigation.label" },
      {
        contracts: ["realms.get", "realms.update"],
        key: "realm",
        path: "/admin/realm",
        title: "shell.nav.realmSettings",
      },
      {
        contracts: ["organizations.branding.get", "organizations.branding.set"],
        key: "branding",
        path: "/admin/branding",
        title: "shell.nav.branding",
      },
      {
        contracts: ["organizations.login-policy.get", "organizations.login-policy.set"],
        key: "login-policy",
        path: "/admin/login-policy",
        title: "shell.nav.loginPolicyProviders",
      },
      {
        contracts: ["organizations.list", "organizations.create"],
        key: "organizations",
        path: "/admin/organizations",
        title: "shell.nav.organizations",
      },
      {
        contracts: ["organizations.get", "organizations.update"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.read",
          realm: "required",
        },
        key: "organization-detail",
        path: "/admin/organizations/:organizationId",
        title: "admin.organizations.detailTitle",
      },
      {
        contracts: ["organizations.memberships.list", "organizations.memberships.update"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.members.manage",
          realm: "required",
        },
        key: "memberships",
        path: "/admin/memberships",
        title: "shell.nav.membershipsRoles",
      },
      {
        contracts: [
          "organizations.invitations.list",
          "organizations.invitations.create",
          "organizations.invitations.revoke",
        ],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.members.manage",
          realm: "required",
        },
        key: "invitations",
        path: "/admin/invitations",
        title: "shell.nav.invitations",
      },
      {
        contracts: ["organizations.domains.list", "organizations.domains.claim", "organizations.domains.verify"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.manage",
          realm: "required",
        },
        key: "domains",
        path: "/admin/domains",
        title: "admin.organizations.domains.title",
      },
      {
        contracts: ["users.list", "users.create"],
        guard: { authentication: "required", organization: "not-required", permission: "user.read", realm: "required" },
        key: "users",
        path: "/admin/users",
        title: "shell.nav.users",
      },
      {
        contracts: [
          "users.get",
          "users.profile",
          "users.lifecycle",
          "users.verification",
          "users.delete",
          "users.authentication-methods",
          "sessions.list",
          "sessions.revoke",
        ],
        guard: { authentication: "required", organization: "not-required", permission: "user.read", realm: "required" },
        key: "user-detail",
        path: "/admin/users/:userId",
        title: "admin.users.detailTitle",
      },
      {
        contracts: ["impersonation.start", "impersonation.end"],
        key: "impersonation",
        path: "/admin/impersonation",
        title: "shell.nav.impersonation",
      },
      {
        contracts: ["projects.list", "projects.create"],
        key: "projects",
        path: "/admin/projects",
        title: "shell.nav.projects",
      },
      {
        contracts: ["projects.get", "projects.update", "projects.delete"],
        key: "project-detail",
        path: "/admin/projects/:projectId",
        title: "admin.projects.detailTitle",
      },
      {
        contracts: ["projects.applications.list", "projects.applications.create", "projects.applications.update"],
        key: "applications",
        path: "/admin/projects/:projectId/applications",
        title: "shell.nav.applications",
      },
      {
        contracts: ["authorization.roles.list", "projects.grants.list", "projects.grants.update"],
        key: "roles-grants",
        path: "/admin/projects/:projectId/roles-grants",
        title: "shell.nav.rolesGrants",
      },
      {
        contracts: ["authorization.evaluate", "projects.access.check"],
        key: "effective-access",
        path: "/admin/projects/:projectId/effective-access",
        title: "admin.projects.access.title",
      },
      {
        contracts: ["oidc.clients.list", "oidc.clients.create", "oidc.clients.update"],
        key: "oidc-clients",
        path: "/admin/oidc-clients",
        title: "shell.nav.oidcClients",
      },
      {
        contracts: ["oidc.clients.get", "oidc.clients.update", "oidc.clients.secret"],
        key: "oidc-client-detail",
        path: "/admin/oidc-clients/:clientId",
        title: "admin.oidc.clients.detailTitle",
      },
      {
        contracts: ["oidc.signing-keys.list", "oidc.signing-keys.rotate"],
        key: "signing-keys",
        path: "/admin/signing-keys",
        title: "shell.nav.signingKeys",
      },
      {
        contracts: ["oidc.consents.list", "oidc.consents.revoke"],
        key: "oidc-consents",
        path: "/admin/oidc-consents",
        title: "shell.nav.applicationConsents",
      },
      {
        contracts: ["oidc.discovery", "oidc.jwks"],
        key: "protocol-documents",
        path: "/admin/protocol-documents",
        title: "shell.nav.protocolDocuments",
      },
      {
        contracts: ["machine-users.list", "machine-users.create", "machine-users.lifecycle"],
        key: "machine-users",
        path: "/admin/machine-users",
        title: "shell.nav.machineUsers",
      },
      {
        contracts: ["machine-users.get", "machine-users.lifecycle", "machine-users.credentials.rotate"],
        key: "machine-user-detail",
        path: "/admin/machine-users/:machineUserId",
        title: "admin.machine.users.detailTitle",
      },
      {
        contracts: [
          "machine-users.credentials.issue",
          "machine-users.credentials.rotate",
          "machine-users.credentials.revoke",
        ],
        key: "machine-credentials",
        path: "/admin/machine-credentials",
        title: "shell.nav.machineCredentials",
      },
      {
        contracts: ["sessions.list", "sessions.revoke"],
        key: "sessions",
        path: "/admin/sessions",
        title: "shell.nav.sessions",
      },
      { contracts: ["events.list"], key: "audit-events", path: "/admin/events", title: "shell.nav.auditEvents" },
    ],
  },
} as const satisfies Readonly<Record<string, ProductionRouteContract>>
