import type { ProductionRouteContract } from "./productionRouteContract.js"

export const productionRouteContractMap = {
  login: {
    feature: "login",
    guard: { authentication: "public", organization: "not-required", permission: null, realm: "required" },
    path: "/login",
    screens: [
      {
        contracts: ["organizations.discovery", "organizations.login-policy", "sessions.recent"],
        key: "chooser",
        path: "/login",
        title: "Sign in",
      },
      { contracts: ["passwords.login"], key: "password", path: "/login/password", title: "Password sign-in" },
      {
        contracts: ["email-otp.start", "email-otp.verify"],
        key: "email-otp",
        path: "/login/email-otp",
        title: "Email code sign-in",
      },
      { contracts: ["passkeys.authenticate"], key: "passkey", path: "/login/passkey", title: "Passkey sign-in" },
      {
        contracts: ["external-identities.authenticate"],
        key: "external-identity",
        path: "/login/idp",
        title: "External identity sign-in",
      },
      { contracts: ["mfa.challenge"], key: "mfa", path: "/login/mfa", title: "Multi-factor sign-in" },
      {
        contracts: ["passwords.recovery.request", "passwords.recovery.complete"],
        key: "recovery",
        path: "/login/password/forgot",
        title: "Password recovery",
      },
      { contracts: ["passwords.register"], key: "register", path: "/login/register", title: "Registration" },
      {
        contracts: ["passwords.verify-email"],
        key: "verify-email",
        path: "/login/verify-email",
        title: "Verify email",
      },
      { contracts: ["oidc.interaction"], key: "consent", path: "/login/consent", title: "Application consent" },
      { contracts: ["oidc.logout"], key: "logout", path: "/login/logout", title: "Logout" },
    ],
  },
  consent: {
    feature: "oidc",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/consent",
    screens: [
      {
        contracts: ["oidc.authorization", "oidc.consent"],
        key: "consent",
        path: "/consent",
        title: "Application consent",
      },
    ],
  },
  account: {
    feature: "account",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/account",
    screens: [
      { contracts: ["account.overview"], key: "overview", path: "/account", title: "Account" },
      { contracts: ["account.profile"], key: "profile", path: "/account/profile", title: "Profile" },
      { contracts: ["account.email"], key: "email", path: "/account/email", title: "Email address" },
      { contracts: ["account.password"], key: "password", path: "/account/password", title: "Password" },
      { contracts: ["account.delete"], key: "delete", path: "/account/delete", title: "Delete account" },
      {
        contracts: ["organizations.list", "organizations.switch"],
        key: "organizations",
        path: "/account/organizations",
        title: "My organizations",
      },
      {
        contracts: ["sessions.list", "sessions.revoke"],
        key: "sessions",
        path: "/account/sessions",
        title: "Sessions and devices",
      },
      {
        contracts: ["passkeys.list", "passkeys.revoke"],
        key: "passkeys",
        path: "/account/passkeys",
        title: "Passkeys",
      },
      {
        contracts: ["mfa.list", "mfa.enroll", "mfa.revoke"],
        key: "factors",
        path: "/account/factors",
        title: "Multi-factor authentication",
      },
      {
        contracts: ["mfa.recovery-codes"],
        key: "recovery-codes",
        path: "/account/recovery-codes",
        title: "Recovery codes",
      },
      {
        contracts: ["external-identities.list", "external-identities.unlink"],
        key: "identities",
        path: "/account/identities",
        title: "Linked identities",
      },
      {
        contracts: ["oidc.consents.list", "oidc.consents.revoke"],
        key: "consents",
        path: "/account/consents",
        title: "Application consents",
      },
    ],
  },
  invitations: {
    feature: "organizations",
    guard: { authentication: "required", organization: "optional", permission: null, realm: "required" },
    path: "/invitations",
    screens: [
      {
        contracts: ["organizations.invitations.accept", "organizations.invitations.decline"],
        key: "overview",
        path: "/invitations",
        title: "Invitations",
      },
      {
        contracts: ["organizations.invitations.accept", "organizations.invitations.decline"],
        key: "accept",
        path: "/invitations/accept",
        title: "Accept invitation",
      },
    ],
  },
  admin: {
    feature: "admin",
    guard: { authentication: "required", organization: "not-required", permission: "realm.read", realm: "required" },
    path: "/admin",
    screens: [
      {
        contracts: ["sessions.admin-sign-in"],
        guard: { authentication: "public", organization: "not-required", permission: null, realm: "required" },
        key: "sign-in",
        path: "/admin/sign-in",
        title: "Administrator sign-in",
      },
      { contracts: ["realms.get"], key: "overview", path: "/admin", title: "Administration" },
      { contracts: ["realms.get", "realms.update"], key: "realm", path: "/admin/realm", title: "Realm settings" },
      {
        contracts: ["organizations.branding.get", "organizations.branding.set"],
        key: "branding",
        path: "/admin/branding",
        title: "Branding",
      },
      {
        contracts: ["organizations.login-policy.get", "organizations.login-policy.set"],
        key: "login-policy",
        path: "/admin/login-policy",
        title: "Login and identity providers",
      },
      {
        contracts: ["organizations.list", "organizations.create"],
        key: "organizations",
        path: "/admin/organizations",
        title: "Organizations",
      },
      {
        contracts: ["organizations.get", "organizations.update"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.read",
          realm: "required",
        },
        key: "organization-detail",
        path: "/admin/organizations/:organizationId",
        title: "Organization detail",
      },
      {
        contracts: ["organizations.memberships.list", "organizations.memberships.update"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.members.manage",
          realm: "required",
        },
        key: "memberships",
        path: "/admin/memberships",
        title: "Memberships and roles",
      },
      {
        contracts: [
          "organizations.invitations.list",
          "organizations.invitations.create",
          "organizations.invitations.revoke",
        ],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.members.manage",
          realm: "required",
        },
        key: "invitations",
        path: "/admin/invitations",
        title: "Invitations",
      },
      {
        contracts: ["organizations.domains.list", "organizations.domains.claim", "organizations.domains.verify"],
        guard: {
          authentication: "required",
          organization: "required",
          permission: "organization.manage",
          realm: "required",
        },
        key: "domains",
        path: "/admin/domains",
        title: "Domains and discovery",
      },
      {
        contracts: ["users.list", "users.create"],
        guard: { authentication: "required", organization: "not-required", permission: "user.read", realm: "required" },
        key: "users",
        path: "/admin/users",
        title: "Users",
      },
      {
        contracts: [
          "users.get",
          "users.profile",
          "users.lifecycle",
          "users.verification",
          "users.delete",
          "users.authentication-methods",
          "sessions.list",
          "sessions.revoke",
        ],
        guard: { authentication: "required", organization: "not-required", permission: "user.read", realm: "required" },
        key: "user-detail",
        path: "/admin/users/:userId",
        title: "User detail",
      },
      {
        contracts: ["impersonation.start", "impersonation.end"],
        key: "impersonation",
        path: "/admin/impersonation",
        title: "Impersonation",
      },
      { contracts: ["projects.list", "projects.create"], key: "projects", path: "/admin/projects", title: "Projects" },
      {
        contracts: ["projects.get", "projects.update", "projects.delete"],
        key: "project-detail",
        path: "/admin/projects/:projectId",
        title: "Project detail",
      },
      {
        contracts: ["projects.applications.list", "projects.applications.create", "projects.applications.update"],
        key: "applications",
        path: "/admin/projects/:projectId/applications",
        title: "Applications",
      },
      {
        contracts: ["authorization.roles.list", "projects.grants.list", "projects.grants.update"],
        key: "roles-grants",
        path: "/admin/projects/:projectId/roles-grants",
        title: "Roles and grants",
      },
      {
        contracts: ["authorization.evaluate", "projects.access.check"],
        key: "effective-access",
        path: "/admin/projects/:projectId/effective-access",
        title: "Effective access",
      },
      {
        contracts: ["oidc.clients.list", "oidc.clients.create", "oidc.clients.update"],
        key: "oidc-clients",
        path: "/admin/oidc-clients",
        title: "OIDC clients",
      },
      {
        contracts: ["oidc.clients.get", "oidc.clients.update", "oidc.clients.secret"],
        key: "oidc-client-detail",
        path: "/admin/oidc-clients/:clientId",
        title: "OIDC client detail",
      },
      {
        contracts: ["oidc.signing-keys.list", "oidc.signing-keys.rotate"],
        key: "signing-keys",
        path: "/admin/signing-keys",
        title: "Signing keys",
      },
      {
        contracts: ["oidc.consents.list", "oidc.consents.revoke"],
        key: "oidc-consents",
        path: "/admin/oidc-consents",
        title: "Application consents",
      },
      {
        contracts: ["oidc.discovery", "oidc.jwks"],
        key: "protocol-documents",
        path: "/admin/protocol-documents",
        title: "Protocol documents",
      },
      {
        contracts: ["machine-users.list", "machine-users.create", "machine-users.lifecycle"],
        key: "machine-users",
        path: "/admin/machine-users",
        title: "Machine users",
      },
      {
        contracts: ["machine-users.get", "machine-users.lifecycle", "machine-users.credentials.rotate"],
        key: "machine-user-detail",
        path: "/admin/machine-users/:machineUserId",
        title: "Machine user detail",
      },
      {
        contracts: [
          "machine-users.credentials.issue",
          "machine-users.credentials.rotate",
          "machine-users.credentials.revoke",
        ],
        key: "machine-credentials",
        path: "/admin/machine-credentials",
        title: "Machine credentials",
      },
      { contracts: ["sessions.list", "sessions.revoke"], key: "sessions", path: "/admin/sessions", title: "Sessions" },
      { contracts: ["events.list"], key: "audit-events", path: "/admin/events", title: "Audit events" },
    ],
  },
} as const satisfies Readonly<Record<string, ProductionRouteContract>>
