import type { ErrorCatalogEntry } from "../../../platform/errors/errorCatalogEntrySchema.js"

export const oidcErrorCatalog = [
  { code: "oidc.invalid", httpStatus: 400, retryable: false },
  { code: "oidc.empty-patch", httpStatus: 400, retryable: false },
  { code: "oidc.invalid-page", httpStatus: 400, retryable: false },
  { code: "oidc.invalid-cursor", httpStatus: 400, retryable: false },
  { code: "oidc.not-found", httpStatus: 404, retryable: false },
  { code: "oidc.unauthorized", httpStatus: 401, retryable: false },
  { code: "oidc.forbidden", httpStatus: 403, retryable: false },
  { code: "oidc.conflict", httpStatus: 409, retryable: false },
  { code: "oidc.already-exists", httpStatus: 409, retryable: false },
  { code: "oidc.not-active", httpStatus: 409, retryable: false },
  { code: "oidc.removed", httpStatus: 409, retryable: false },
  { code: "oidc.cannot-change", httpStatus: 409, retryable: false },
  { code: "oidc.read-failed", httpStatus: 503, retryable: true },
  { code: "oidc.write-failed", httpStatus: 503, retryable: true },
  { code: "oidc.event-invalid", httpStatus: 500, retryable: false },
  { code: "oidc.tenant-mismatch", httpStatus: 404, retryable: false },
  { code: "oidc.configuration-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.client-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.consent-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.redirect-uri-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.redirect-uri-not-registered", httpStatus: 400, retryable: false },
  { code: "oidc.scope-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.invalid-client", httpStatus: 401, retryable: false },
  { code: "oidc.invalid-token", httpStatus: 401, retryable: false },
  { code: "oidc.invalid-grant", httpStatus: 400, retryable: false },
  { code: "oidc.invalid-scope", httpStatus: 400, retryable: false },
  { code: "oidc.invalid-request", httpStatus: 400, retryable: false },
  { code: "oidc.authorization-interaction-required", httpStatus: 400, retryable: false },
  { code: "oidc.authorization-consent-required", httpStatus: 400, retryable: false },
  { code: "oidc.request-invalid", httpStatus: 400, retryable: false },
  { code: "oidc.timestamp-invalid", httpStatus: 500, retryable: false },
  { code: "oidc.invalid-timestamp", httpStatus: 500, retryable: false },
  { code: "oidc.internal", httpStatus: 500, retryable: false },
] as const satisfies readonly ErrorCatalogEntry[]
