import type { ErrorCatalogEntry } from "../../../platform/errors/errorCatalogEntrySchema.js"

export const organizationsErrorCatalog = [
  { code: "organizations.not-found", httpStatus: 404, retryable: false },
  { code: "organizations.tenant-mismatch", httpStatus: 404, retryable: false },
  { code: "organizations.unauthorized", httpStatus: 401, retryable: false },
  { code: "organizations.forbidden", httpStatus: 403, retryable: false },
  { code: "organizations.invalid", httpStatus: 400, retryable: false },
  { code: "organizations.empty-patch", httpStatus: 400, retryable: false },
  { code: "organizations.conflict", httpStatus: 409, retryable: false },
  { code: "organizations.already-exists", httpStatus: 409, retryable: false },
  { code: "organizations.not-member", httpStatus: 403, retryable: false },
  { code: "organizations.must-retain", httpStatus: 409, retryable: false },
  { code: "organizations.not-active", httpStatus: 409, retryable: false },
  { code: "organizations.expired", httpStatus: 409, retryable: false },
  { code: "organizations.pending", httpStatus: 409, retryable: false },
  { code: "organizations.read-failed", httpStatus: 500, retryable: false },
  { code: "organizations.write-failed", httpStatus: 500, retryable: false },
  { code: "organizations.event-invalid", httpStatus: 500, retryable: false },
  { code: "organizations.invalid-timestamp", httpStatus: 400, retryable: false },
  { code: "organizations.system-required", httpStatus: 403, retryable: false },
  { code: "organizations.invalid-domain", httpStatus: 400, retryable: false },
  { code: "organizations.domain-assigned", httpStatus: 409, retryable: false },
  { code: "organizations.domain-not-found", httpStatus: 404, retryable: false },
  { code: "organizations.verification-failed", httpStatus: 409, retryable: false },
  { code: "organizations.state-changed", httpStatus: 409, retryable: false },
  { code: "organizations.invalid-expiry", httpStatus: 400, retryable: false },
  { code: "organizations.login-method-disabled", httpStatus: 409, retryable: false },
  { code: "organizations.provider-disabled", httpStatus: 409, retryable: false },
  { code: "organizations.policy-malformed", httpStatus: 500, retryable: false },
] as const satisfies readonly ErrorCatalogEntry[]
